/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 chair.gltf --transform
Author: Araon (https://sketchfab.com/araon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rustic-chair-77afa26a76614fc2b8ed845024af0b58
Title: Rustic chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert7SG} position={[-253.68, 910.56, -417.56]} />
      </group>
    </group>
  )
}

useGLTF.preload('/chair-transformed.glb')
